"""
sage_worker_daemon.sage  —  Long-running Sage daemon that reads n values from
stdin, one per line, and writes results to stdout.

Protocol:
  input:  "SEARCH <n>"  → compute integral points for E_n, write results
  output: "RESULT <n> <x> <y>"  for each integral point (one per line)
          "DONE <n>"            when finished with n
          "ERROR <n> <msg>"     on errors
          "TIMEOUT"             should never happen here (handled by caller)

Run via:
  sage sage_worker_daemon.sage

The orchestrator (sage_orchestrator.py) spawns this and talks to it via pipes.
"""


# This file was *autogenerated* from the file /Users/jamalmac/Desktop/sumsof3cubes/ec_curve/sage_worker_daemon.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1296 = Integer(1296); _sage_const_2 = Integer(2); _sage_const_15552 = Integer(15552); _sage_const_3 = Integer(3); _sage_const_46656 = Integer(46656); _sage_const_4 = Integer(4); _sage_const_19 = Integer(19); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1)
import sys
sys.stdout.reconfigure(line_buffering=True)
sys.stderr.reconfigure(line_buffering=True)

def process_n(n):
    n = Integer(n)
    a2 = _sage_const_1296  * n**_sage_const_2 
    a4 = _sage_const_15552  * n**_sage_const_3 
    a6 = _sage_const_46656  * n**_sage_const_4  - _sage_const_19 *n
    E = EllipticCurve(QQ, [_sage_const_0 , a2, _sage_const_0 , a4, a6])
    if E.discriminant() == _sage_const_0 :
        print(f"DONE {n}", flush=True)
        return
    try:
        r = E.rank(proof=False)
    except Exception as e:
        print(f"ERROR {n} rank_failed:{e}", flush=True)
        r = _sage_const_0 
    mw = []
    if r > _sage_const_0 :
        try:
            mw = E.gens(proof=False)
        except Exception as e:
            print(f"ERROR {n} gens_failed:{e}", flush=True)
            mw = []
    try:
        pts = E.integral_points(mw_base=mw, both_signs=True)
    except Exception as e:
        print(f"ERROR {n} integral_pts:{e}", flush=True)
        print(f"DONE {n}", flush=True)
        return
    for pt in pts:
        if pt.is_infinity():
            continue
        x, y = int(pt[_sage_const_0 ]), int(pt[_sage_const_1 ])
        lhs = y*y
        rhs = int(x**_sage_const_3  + _sage_const_1296 *n**_sage_const_2 *x**_sage_const_2  + _sage_const_15552 *n**_sage_const_3 *x + _sage_const_46656 *n**_sage_const_4  - _sage_const_19 *n)
        if lhs == rhs:
            print(f"RESULT {int(n)} {x} {y}", flush=True)
        else:
            print(f"ERROR {n} verify_fail x={x} y={y}", flush=True)
    print(f"DONE {n}", flush=True)

print("READY", flush=True)
for line in sys.stdin:
    line = line.strip()
    if not line:
        continue
    if line.startswith("SEARCH "):
        n_val = int(line.split()[_sage_const_1 ])
        try:
            process_n(n_val)
        except Exception as e:
            print(f"ERROR {n_val} exception:{e}", flush=True)
            print(f"DONE {n_val}", flush=True)
    elif line == "QUIT":
        break

print("BYE", flush=True)

