

# This file was *autogenerated* from the file /Users/jamalmac/Desktop/sumsof3cubes/ec_curve/sage_one_n.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_1296 = Integer(1296); _sage_const_2 = Integer(2); _sage_const_15552 = Integer(15552); _sage_const_3 = Integer(3); _sage_const_46656 = Integer(46656); _sage_const_4 = Integer(4); _sage_const_19 = Integer(19); _sage_const_0 = Integer(0)# sage_one_n.sage  —  search one n, print "SOLUTION n x y" lines
import sys
n = Integer(sys.argv[_sage_const_1 ])
a2 = _sage_const_1296 *n**_sage_const_2 
a4 = _sage_const_15552 *n**_sage_const_3 
a6 = _sage_const_46656 *n**_sage_const_4  - _sage_const_19 *n
E = EllipticCurve(QQ, [_sage_const_0 , a2, _sage_const_0 , a4, a6])
if E.discriminant() == _sage_const_0 :
    sys.exit(_sage_const_0 )
try:
    r = E.rank(proof=False)
except Exception:
    r = _sage_const_0 
mw = []
if r > _sage_const_0 :
    try:
        mw = E.gens(proof=False)
    except Exception:
        mw = []
try:
    pts = E.integral_points(mw_base=mw, both_signs=True)
except Exception as e:
    print(f"WARN integral_points n={n}: {e}", file=sys.stderr)
    sys.exit(_sage_const_0 )
for pt in pts:
    if pt.is_infinity():
        continue
    x, y = int(pt[_sage_const_0 ]), int(pt[_sage_const_1 ])
    lhs = y**_sage_const_2 
    rhs = int(x**_sage_const_3  + _sage_const_1296 *n**_sage_const_2 *x**_sage_const_2  + _sage_const_15552 *n**_sage_const_3 *x + _sage_const_46656 *n**_sage_const_4  - _sage_const_19 *n)
    if lhs == rhs:
        print(f"SOLUTION {n} {x} {y}")
    else:
        print(f"WARN verify fail n={n} x={x} y={y}", file=sys.stderr)

